# -*- coding: utf-8 -*-
"""Frailty-Analysis (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwciA4J8YdC258XaKZlubKqJqZOM-Pip
"""

import pandas as pd

# loading clean data for analysis

df = pd.read_csv("FrailtyData.csv")

print(df.to_string())

df.info()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# below graph shows the distribution of Age in the given data

# Create a line plot for 'Age'
plt.figure(figsize=(10,6))
ax = sns.lineplot(data=df, x=df.index, y='Age', color='blue')

# Set the title and labels
plt.title('Line Plot of Age')
plt.xlabel('Index')
plt.ylabel('Age')

# Save the plot as a PNG file
fig = ax.get_figure()
fig.savefig("Age_Line_Plot.png")

plt.show()

# below graph shows the distribution of Gripstrength in the given data

ax=sns.distplot(df['Grip Strength'], kde = False, color ='coral', bins = 30)
fig=ax.get_figure()
fig.savefig("Grip_Strength_Distibution.png")

#below graph shows how the gripstrength increases with age and decreases after certain age

# Create a scatter plot using Seaborn
plt.figure(figsize=(10,6))
ax = sns.scatterplot(data=df, x='Age', y='Grip Strength', color='blue')

# Set the title and labels
plt.title('Relationship between Age and Grip Strength')
plt.xlabel('Age')
plt.ylabel('Grip Strength')

# Save the plot as a PNG file
fig = ax.get_figure()
fig.savefig("Grip_Strength_Age_Relation.png")

plt.show()

# below graph shows the relation between gripstrength and weight and how iut varies on weight.

# Create a box plot using Seaborn
plt.figure(figsize=(10,6))
ax = sns.boxplot(x='Weight', y='Grip Strength', data=df)

# Set the title and labels
plt.title('Box Plot: Relationship between Weight and Grip Strength')
plt.xlabel('Weight')
plt.ylabel('Grip Strength')

# Save the plot as a PNG file
fig = ax.get_figure()
fig.savefig("GripStrength_Weight_BoxPlot.png")

plt.show()



